version: '3.1'

services:
  mongo:
    image: mongo:4.0.4
    ports: 
      - "27017:27017"
    restart: always

  py-image:
    user: root
    build:
      dockerfile: Dockerfile
      context: ./
    ports: 
      - 5555:5555
    volumes: 
      - ./:/usr/src/app
    links:
      - mongo
    depends_on: 
      - mongo

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: 192.168.101.126