version: '3.1'

services:
  mongo:
    image: mongo:4.0.4
    ports: 
      - "27017:27017"
    restart: always
    networks: 
      rede-project:
        ipv4_address: 10.0.0.2

  py-image:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    ports: 
      - 5555:5555
    volumes: 
      - ./:/usr/src/app
    links:
      - mongo
    depends_on: 
      - mongo
    networks: 
      rede-project:
        ipv4_address: 10.0.0.3

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    networks: 
      rede-project:
        ipv4_address: 10.0.0.4

networks: 
  rede-project:
    driver: bridge
    ipam:
      config: 
        - subnet: 10.0.0.0/16